<?php

// Script untuk fix semua halaman agar konsisten dengan tema monokrom
$replacements = [
    // Text colors - semua ke neutral
    'text-white' => 'text-neutral-text',
    'text-gray-900' => 'text-neutral-text',
    'text-gray-800' => 'text-neutral-text',
    'text-gray-700' => 'text-neutral-text',
    'text-gray-600' => 'text-neutral-sub',
    'text-gray-500' => 'text-neutral-sub',
    'text-gray-400' => 'text-neutral-sub',
    'text-gray-300' => 'text-neutral-sub',
    'text-gray-200' => 'text-neutral-sub',
    'text-gray-100' => 'text-neutral-sub',
    
    // Background colors - semua ke neutral/white
    'bg-slate-900' => 'bg-neutral-bg',
    'bg-slate-800' => 'bg-white',
    'bg-slate-700' => 'bg-white',
    'bg-slate-600' => 'bg-white',
    'bg-slate-500' => 'bg-white',
    'bg-slate-400' => 'bg-white',
    'bg-slate-300' => 'bg-neutral-line',
    'bg-slate-200' => 'bg-neutral-line',
    'bg-slate-100' => 'bg-white',
    'bg-slate-50' => 'bg-white',
    
    'bg-gray-900' => 'bg-neutral-bg',
    'bg-gray-800' => 'bg-white',
    'bg-gray-700' => 'bg-white',
    'bg-gray-600' => 'bg-white',
    'bg-gray-500' => 'bg-white',
    'bg-gray-400' => 'bg-white',
    'bg-gray-300' => 'bg-neutral-line',
    'bg-gray-200' => 'bg-neutral-line',
    'bg-gray-100' => 'bg-white',
    'bg-gray-50' => 'bg-white',
    
    // Warna-warni dihapus - ganti ke neutral
    'bg-emerald-50' => 'bg-white',
    'bg-emerald-100' => 'bg-white',
    'bg-emerald-200' => 'bg-neutral-line',
    'bg-emerald-300' => 'bg-neutral-line',
    'bg-emerald-400' => 'bg-neutral-line',
    'bg-emerald-500' => 'bg-neutral-line',
    'bg-emerald-600' => 'bg-neutral-line',
    'bg-emerald-700' => 'bg-neutral-line',
    'bg-emerald-800' => 'bg-neutral-line',
    'bg-emerald-900' => 'bg-neutral-line',
    
    'text-emerald-50' => 'text-neutral-sub',
    'text-emerald-100' => 'text-neutral-sub',
    'text-emerald-200' => 'text-neutral-sub',
    'text-emerald-300' => 'text-neutral-sub',
    'text-emerald-400' => 'text-neutral-sub',
    'text-emerald-500' => 'text-neutral-sub',
    'text-emerald-600' => 'text-neutral-sub',
    'text-emerald-700' => 'text-neutral-sub',
    'text-emerald-800' => 'text-neutral-sub',
    'text-emerald-900' => 'text-neutral-sub',
    
    'bg-amber-50' => 'bg-white',
    'bg-amber-100' => 'bg-white',
    'bg-amber-200' => 'bg-neutral-line',
    'bg-amber-300' => 'bg-neutral-line',
    'bg-amber-400' => 'bg-neutral-line',
    'bg-amber-500' => 'bg-neutral-line',
    'bg-amber-600' => 'bg-neutral-line',
    'bg-amber-700' => 'bg-neutral-line',
    'bg-amber-800' => 'bg-neutral-line',
    'bg-amber-900' => 'bg-neutral-line',
    
    'text-amber-50' => 'text-neutral-sub',
    'text-amber-100' => 'text-neutral-sub',
    'text-amber-200' => 'text-neutral-sub',
    'text-amber-300' => 'text-neutral-sub',
    'text-amber-400' => 'text-neutral-sub',
    'text-amber-500' => 'text-neutral-sub',
    'text-amber-600' => 'text-neutral-sub',
    'text-amber-700' => 'text-neutral-sub',
    'text-amber-800' => 'text-neutral-sub',
    'text-amber-900' => 'text-neutral-sub',
    
    'bg-rose-50' => 'bg-white',
    'bg-rose-100' => 'bg-white',
    'bg-rose-200' => 'bg-neutral-line',
    'bg-rose-300' => 'bg-neutral-line',
    'bg-rose-400' => 'bg-neutral-line',
    'bg-rose-500' => 'bg-neutral-line',
    'bg-rose-600' => 'bg-neutral-line',
    'bg-rose-700' => 'bg-neutral-line',
    'bg-rose-800' => 'bg-neutral-line',
    'bg-rose-900' => 'bg-neutral-line',
    
    'text-rose-50' => 'text-neutral-sub',
    'text-rose-100' => 'text-neutral-sub',
    'text-rose-200' => 'text-neutral-sub',
    'text-rose-300' => 'text-neutral-sub',
    'text-rose-400' => 'text-neutral-sub',
    'text-rose-500' => 'text-neutral-sub',
    'text-rose-600' => 'text-neutral-sub',
    'text-rose-700' => 'text-neutral-sub',
    'text-rose-800' => 'text-neutral-sub',
    'text-rose-900' => 'text-neutral-sub',
    
    // Warna lain yang bermasalah
    'bg-blue-50' => 'bg-white',
    'bg-blue-100' => 'bg-white',
    'bg-blue-200' => 'bg-neutral-line',
    'bg-blue-300' => 'bg-neutral-line',
    'bg-blue-400' => 'bg-neutral-line',
    'bg-blue-500' => 'bg-neutral-line',
    'bg-blue-600' => 'bg-neutral-line',
    'bg-blue-700' => 'bg-neutral-line',
    'bg-blue-800' => 'bg-neutral-line',
    'bg-blue-900' => 'bg-neutral-line',
    
    'text-blue-50' => 'text-neutral-sub',
    'text-blue-100' => 'text-neutral-sub',
    'text-blue-200' => 'text-neutral-sub',
    'text-blue-300' => 'text-neutral-sub',
    'text-blue-400' => 'text-neutral-sub',
    'text-blue-500' => 'text-neutral-sub',
    'text-blue-600' => 'text-neutral-sub',
    'text-blue-700' => 'text-neutral-sub',
    'text-blue-800' => 'text-neutral-sub',
    'text-blue-900' => 'text-neutral-sub',
    
    'bg-green-50' => 'bg-white',
    'bg-green-100' => 'bg-white',
    'bg-green-200' => 'bg-neutral-line',
    'bg-green-300' => 'bg-neutral-line',
    'bg-green-400' => 'bg-neutral-line',
    'bg-green-500' => 'bg-neutral-line',
    'bg-green-600' => 'bg-neutral-line',
    'bg-green-700' => 'bg-neutral-line',
    'bg-green-800' => 'bg-neutral-line',
    'bg-green-900' => 'bg-neutral-line',
    
    'text-green-50' => 'text-neutral-sub',
    'text-green-100' => 'text-neutral-sub',
    'text-green-200' => 'text-neutral-sub',
    'text-green-300' => 'text-neutral-sub',
    'text-green-400' => 'text-neutral-sub',
    'text-green-500' => 'text-neutral-sub',
    'text-green-600' => 'text-neutral-sub',
    'text-green-700' => 'text-neutral-sub',
    'text-green-800' => 'text-neutral-sub',
    'text-green-900' => 'text-neutral-sub',
    
    'bg-red-50' => 'bg-white',
    'bg-red-100' => 'bg-white',
    'bg-red-200' => 'bg-neutral-line',
    'bg-red-300' => 'bg-neutral-line',
    'bg-red-400' => 'bg-neutral-line',
    'bg-red-500' => 'bg-neutral-line',
    'bg-red-600' => 'bg-neutral-line',
    'bg-red-700' => 'bg-neutral-line',
    'bg-red-800' => 'bg-neutral-line',
    'bg-red-900' => 'bg-neutral-line',
    
    'text-red-50' => 'text-neutral-sub',
    'text-red-100' => 'text-neutral-sub',
    'text-red-200' => 'text-neutral-sub',
    'text-red-300' => 'text-neutral-sub',
    'text-red-400' => 'text-neutral-sub',
    'text-red-500' => 'text-neutral-sub',
    'text-red-600' => 'text-neutral-sub',
    'text-red-700' => 'text-neutral-sub',
    'text-red-800' => 'text-neutral-sub',
    'text-red-900' => 'text-neutral-sub',
    
    'bg-yellow-50' => 'bg-white',
    'bg-yellow-100' => 'bg-white',
    'bg-yellow-200' => 'bg-neutral-line',
    'bg-yellow-300' => 'bg-neutral-line',
    'bg-yellow-400' => 'bg-neutral-line',
    'bg-yellow-500' => 'bg-neutral-line',
    'bg-yellow-600' => 'bg-neutral-line',
    'bg-yellow-700' => 'bg-neutral-line',
    'bg-yellow-800' => 'bg-neutral-line',
    'bg-yellow-900' => 'bg-neutral-line',
    
    'text-yellow-50' => 'text-neutral-sub',
    'text-yellow-100' => 'text-neutral-sub',
    'text-yellow-200' => 'text-neutral-sub',
    'text-yellow-300' => 'text-neutral-sub',
    'text-yellow-400' => 'text-neutral-sub',
    'text-yellow-500' => 'text-neutral-sub',
    'text-yellow-600' => 'text-neutral-sub',
    'text-yellow-700' => 'text-neutral-sub',
    'text-yellow-800' => 'text-neutral-sub',
    'text-yellow-900' => 'text-neutral-sub',
    
    'bg-purple-50' => 'bg-white',
    'bg-purple-100' => 'bg-white',
    'bg-purple-200' => 'bg-neutral-line',
    'bg-purple-300' => 'bg-neutral-line',
    'bg-purple-400' => 'bg-neutral-line',
    'bg-purple-500' => 'bg-neutral-line',
    'bg-purple-600' => 'bg-neutral-line',
    'bg-purple-700' => 'bg-neutral-line',
    'bg-purple-800' => 'bg-neutral-line',
    'bg-purple-900' => 'bg-neutral-line',
    
    'text-purple-50' => 'text-neutral-sub',
    'text-purple-100' => 'text-neutral-sub',
    'text-purple-200' => 'text-neutral-sub',
    'text-purple-300' => 'text-neutral-sub',
    'text-purple-400' => 'text-neutral-sub',
    'text-purple-500' => 'text-neutral-sub',
    'text-purple-600' => 'text-neutral-sub',
    'text-purple-700' => 'text-neutral-sub',
    'text-purple-800' => 'text-neutral-sub',
    'text-purple-900' => 'text-neutral-sub',
    
    'bg-pink-50' => 'bg-white',
    'bg-pink-100' => 'bg-white',
    'bg-pink-200' => 'bg-neutral-line',
    'bg-pink-300' => 'bg-neutral-line',
    'bg-pink-400' => 'bg-neutral-line',
    'bg-pink-500' => 'bg-neutral-line',
    'bg-pink-600' => 'bg-neutral-line',
    'bg-pink-700' => 'bg-neutral-line',
    'bg-pink-800' => 'bg-neutral-line',
    'bg-pink-900' => 'bg-neutral-line',
    
    'text-pink-50' => 'text-neutral-sub',
    'text-pink-100' => 'text-neutral-sub',
    'text-pink-200' => 'text-neutral-sub',
    'text-pink-300' => 'text-neutral-sub',
    'text-pink-400' => 'text-neutral-sub',
    'text-pink-500' => 'text-neutral-sub',
    'text-pink-600' => 'text-neutral-sub',
    'text-pink-700' => 'text-neutral-sub',
    'text-pink-800' => 'text-neutral-sub',
    'text-pink-900' => 'text-neutral-sub',
    
    'bg-indigo-50' => 'bg-white',
    'bg-indigo-100' => 'bg-white',
    'bg-indigo-200' => 'bg-neutral-line',
    'bg-indigo-300' => 'bg-neutral-line',
    'bg-indigo-400' => 'bg-neutral-line',
    'bg-indigo-500' => 'bg-neutral-line',
    'bg-indigo-600' => 'bg-neutral-line',
    'bg-indigo-700' => 'bg-neutral-line',
    'bg-indigo-800' => 'bg-neutral-line',
    'bg-indigo-900' => 'bg-neutral-line',
    
    'text-indigo-50' => 'text-neutral-sub',
    'text-indigo-100' => 'text-neutral-sub',
    'text-indigo-200' => 'text-neutral-sub',
    'text-indigo-300' => 'text-neutral-sub',
    'text-indigo-400' => 'text-neutral-sub',
    'text-indigo-500' => 'text-neutral-sub',
    'text-indigo-600' => 'text-neutral-sub',
    'text-indigo-700' => 'text-neutral-sub',
    'text-indigo-800' => 'text-neutral-sub',
    'text-indigo-900' => 'text-neutral-sub',
    
    'bg-cyan-50' => 'bg-white',
    'bg-cyan-100' => 'bg-white',
    'bg-cyan-200' => 'bg-neutral-line',
    'bg-cyan-300' => 'bg-neutral-line',
    'bg-cyan-400' => 'bg-neutral-line',
    'bg-cyan-500' => 'bg-neutral-line',
    'bg-cyan-600' => 'bg-neutral-line',
    'bg-cyan-700' => 'bg-neutral-line',
    'bg-cyan-800' => 'bg-neutral-line',
    'bg-cyan-900' => 'bg-neutral-line',
    
    'text-cyan-50' => 'text-neutral-sub',
    'text-cyan-100' => 'text-neutral-sub',
    'text-cyan-200' => 'text-neutral-sub',
    'text-cyan-300' => 'text-neutral-sub',
    'text-cyan-400' => 'text-neutral-sub',
    'text-cyan-500' => 'text-neutral-sub',
    'text-cyan-600' => 'text-neutral-sub',
    'text-cyan-700' => 'text-neutral-sub',
    'text-cyan-800' => 'text-neutral-sub',
    'text-cyan-900' => 'text-neutral-sub',
    
    'bg-teal-50' => 'bg-white',
    'bg-teal-100' => 'bg-white',
    'bg-teal-200' => 'bg-neutral-line',
    'bg-teal-300' => 'bg-neutral-line',
    'bg-teal-400' => 'bg-neutral-line',
    'bg-teal-500' => 'bg-neutral-line',
    'bg-teal-600' => 'bg-neutral-line',
    'bg-teal-700' => 'bg-neutral-line',
    'bg-teal-800' => 'bg-neutral-line',
    'bg-teal-900' => 'bg-neutral-line',
    
    'text-teal-50' => 'text-neutral-sub',
    'text-teal-100' => 'text-neutral-sub',
    'text-teal-200' => 'text-neutral-sub',
    'text-teal-300' => 'text-neutral-sub',
    'text-teal-400' => 'text-neutral-sub',
    'text-teal-500' => 'text-neutral-sub',
    'text-teal-600' => 'text-neutral-sub',
    'text-teal-700' => 'text-neutral-sub',
    'text-teal-800' => 'text-neutral-sub',
    'text-teal-900' => 'text-neutral-sub',
    
    'bg-orange-50' => 'bg-white',
    'bg-orange-100' => 'bg-white',
    'bg-orange-200' => 'bg-neutral-line',
    'bg-orange-300' => 'bg-neutral-line',
    'bg-orange-400' => 'bg-neutral-line',
    'bg-orange-500' => 'bg-neutral-line',
    'bg-orange-600' => 'bg-neutral-line',
    'bg-orange-700' => 'bg-neutral-line',
    'bg-orange-800' => 'bg-neutral-line',
    'bg-orange-900' => 'bg-neutral-line',
    
    'text-orange-50' => 'text-neutral-sub',
    'text-orange-100' => 'text-neutral-sub',
    'text-orange-200' => 'text-neutral-sub',
    'text-orange-300' => 'text-neutral-sub',
    'text-orange-400' => 'text-neutral-sub',
    'text-orange-500' => 'text-neutral-sub',
    'text-orange-600' => 'text-neutral-sub',
    'text-orange-700' => 'text-neutral-sub',
    'text-orange-800' => 'text-neutral-sub',
    'text-orange-900' => 'text-neutral-sub',
    
    'bg-lime-50' => 'bg-white',
    'bg-lime-100' => 'bg-white',
    'bg-lime-200' => 'bg-neutral-line',
    'bg-lime-300' => 'bg-neutral-line',
    'bg-lime-400' => 'bg-neutral-line',
    'bg-lime-500' => 'bg-neutral-line',
    'bg-lime-600' => 'bg-neutral-line',
    'bg-lime-700' => 'bg-neutral-line',
    'bg-lime-800' => 'bg-neutral-line',
    'bg-lime-900' => 'bg-neutral-line',
    
    'text-lime-50' => 'text-neutral-sub',
    'text-lime-100' => 'text-neutral-sub',
    'text-lime-200' => 'text-neutral-sub',
    'text-lime-300' => 'text-neutral-sub',
    'text-lime-400' => 'text-neutral-sub',
    'text-lime-500' => 'text-neutral-sub',
    'text-lime-600' => 'text-neutral-sub',
    'text-lime-700' => 'text-neutral-sub',
    'text-lime-800' => 'text-neutral-sub',
    'text-lime-900' => 'text-neutral-sub',
    
    'bg-violet-50' => 'bg-white',
    'bg-violet-100' => 'bg-white',
    'bg-violet-200' => 'bg-neutral-line',
    'bg-violet-300' => 'bg-neutral-line',
    'bg-violet-400' => 'bg-neutral-line',
    'bg-violet-500' => 'bg-neutral-line',
    'bg-violet-600' => 'bg-neutral-line',
    'bg-violet-700' => 'bg-neutral-line',
    'bg-violet-800' => 'bg-neutral-line',
    'bg-violet-900' => 'bg-neutral-line',
    
    'text-violet-50' => 'text-neutral-sub',
    'text-violet-100' => 'text-neutral-sub',
    'text-violet-200' => 'text-neutral-sub',
    'text-violet-300' => 'text-neutral-sub',
    'text-violet-400' => 'text-neutral-sub',
    'text-violet-500' => 'text-neutral-sub',
    'text-violet-600' => 'text-neutral-sub',
    'text-violet-700' => 'text-neutral-sub',
    'text-violet-800' => 'text-neutral-sub',
    'text-violet-900' => 'text-neutral-sub',
    
    'bg-fuchsia-50' => 'bg-white',
    'bg-fuchsia-100' => 'bg-white',
    'bg-fuchsia-200' => 'bg-neutral-line',
    'bg-fuchsia-300' => 'bg-neutral-line',
    'bg-fuchsia-400' => 'bg-neutral-line',
    'bg-fuchsia-500' => 'bg-neutral-line',
    'bg-fuchsia-600' => 'bg-neutral-line',
    'bg-fuchsia-700' => 'bg-neutral-line',
    'bg-fuchsia-800' => 'bg-neutral-line',
    'bg-fuchsia-900' => 'bg-neutral-line',
    
    'text-fuchsia-50' => 'text-neutral-sub',
    'text-fuchsia-100' => 'text-neutral-sub',
    'text-fuchsia-200' => 'text-neutral-sub',
    'text-fuchsia-300' => 'text-neutral-sub',
    'text-fuchsia-400' => 'text-neutral-sub',
    'text-fuchsia-500' => 'text-neutral-sub',
    'text-fuchsia-600' => 'text-neutral-sub',
    'text-fuchsia-700' => 'text-neutral-sub',
    'text-fuchsia-800' => 'text-neutral-sub',
    'text-fuchsia-900' => 'text-neutral-sub',
    
    'bg-sky-50' => 'bg-white',
    'bg-sky-100' => 'bg-white',
    'bg-sky-200' => 'bg-neutral-line',
    'bg-sky-300' => 'bg-neutral-line',
    'bg-sky-400' => 'bg-neutral-line',
    'bg-sky-500' => 'bg-neutral-line',
    'bg-sky-600' => 'bg-neutral-line',
    'bg-sky-700' => 'bg-neutral-line',
    'bg-sky-800' => 'bg-neutral-line',
    'bg-sky-900' => 'bg-neutral-line',
    
    'text-sky-50' => 'text-neutral-sub',
    'text-sky-100' => 'text-neutral-sub',
    'text-sky-200' => 'text-neutral-sub',
    'text-sky-300' => 'text-neutral-sub',
    'text-sky-400' => 'text-neutral-sub',
    'text-sky-500' => 'text-neutral-sub',
    'text-sky-600' => 'text-neutral-sub',
    'text-sky-700' => 'text-neutral-sub',
    'text-sky-800' => 'text-neutral-sub',
    'text-sky-900' => 'text-neutral-sub',
    
    // Border colors
    'border-gray-200' => 'border-neutral-line',
    'border-gray-300' => 'border-neutral-line',
    'border-gray-400' => 'border-neutral-line',
    'border-gray-500' => 'border-neutral-line',
    'border-gray-600' => 'border-neutral-line',
    'border-gray-700' => 'border-neutral-line',
    'border-gray-800' => 'border-neutral-line',
    'border-gray-900' => 'border-neutral-line',
    
    'border-slate-200' => 'border-neutral-line',
    'border-slate-300' => 'border-neutral-line',
    'border-slate-400' => 'border-neutral-line',
    'border-slate-500' => 'border-neutral-line',
    'border-slate-600' => 'border-neutral-line',
    'border-slate-700' => 'border-neutral-line',
    'border-slate-800' => 'border-neutral-line',
    'border-slate-900' => 'border-neutral-line',
    
    // Brand colors - konsistensi
    'text-brand-600' => 'text-brand',
    'text-brand-700' => 'text-brand',
    'text-brand-800' => 'text-brand',
    'text-brand-900' => 'text-brand',
    'bg-brand-600' => 'bg-brand',
    'bg-brand-700' => 'bg-brand',
    'bg-brand-800' => 'bg-brand',
    'bg-brand-900' => 'bg-brand',
    'hover:bg-brand-700' => 'hover:opacity-90',
    'hover:bg-brand-800' => 'hover:opacity-90',
    'hover:bg-brand-900' => 'hover:opacity-90',
    'focus:border-brand-500' => 'focus:border-brand',
    'focus:ring-brand-200' => 'focus:ring-brand/20',
    'focus:ring-brand-300' => 'focus:ring-brand/20',
    'focus:ring-brand-400' => 'focus:ring-brand/20',
    
    // Shadow
    'shadow-sm' => 'shadow-soft',
    'shadow-md' => 'shadow-soft',
    'shadow-lg' => 'shadow-soft',
    'shadow-xl' => 'shadow-soft',
    'shadow-2xl' => 'shadow-soft',
    
    // Spacing - konsistensi
    'px-4 sm:px-6 lg:px-8' => 'px-4',
    'py-12' => 'py-10',
    'py-16' => 'py-12',
    'py-20' => 'py-16',
    'py-24' => 'py-20',
    
    // Typography - konsistensi
    'font-display' => 'font-semibold',
    'font-body' => '',
    'text-4xl' => 'text-3xl',
    'text-5xl' => 'text-4xl',
    'text-6xl' => 'text-5xl',
    
    // Remove problematic classes
    'from-' => '',
    'to-' => '',
    'gradient' => '',
    'bg-gradient-to-r' => 'bg-brand',
    'bg-gradient-to-l' => 'bg-brand',
    'bg-gradient-to-t' => 'bg-brand',
    'bg-gradient-to-b' => 'bg-brand',
    'bg-gradient-to-tr' => 'bg-brand',
    'bg-gradient-to-tl' => 'bg-brand',
    'bg-gradient-to-br' => 'bg-brand',
    'bg-gradient-to-bl' => 'bg-brand',
];

// Dapatkan semua file blade
$files = glob('resources/views/**/*.blade.php');

echo "=== FIXING ALL PAGES FOR MONOCHROME CONSISTENCY ===\n\n";

$processed = 0;
$fixed = 0;

foreach ($files as $file) {
    if (file_exists($file)) {
        echo "Processing: " . basename($file) . "\n";
        $content = file_get_contents($file);
        $originalContent = $content;
        
        foreach ($replacements as $old => $new) {
            $content = str_replace($old, $new, $content);
        }
        
        if ($content !== $originalContent) {
            file_put_contents($file, $content);
            echo "✅ Fixed: " . basename($file) . "\n";
            $fixed++;
        } else {
            echo "✅ Clean: " . basename($file) . "\n";
        }
        
        $processed++;
    }
}

echo "\n=== MONOCHROME FIX COMPLETED ===\n";
echo "Processed: {$processed} files\n";
echo "Fixed: {$fixed} files\n";
echo "Clean: " . ($processed - $fixed) . " files\n";

echo "\n🎨 All pages now have consistent monochrome theme!\n";
echo "✅ No more 'alay' colors or inconsistent styling\n";
echo "✅ Professional, clean appearance across all pages\n";
echo "✅ Single accent color (brand) for consistency\n";
echo "✅ Neutral palette for all backgrounds and text\n";
echo "✅ Functional colors (ok/danger) only for status\n";
